apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todos-api-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: todos-api/todos-api-prod.yaml
    target:
      kind: Deployment
      name: todo-api